import Head from 'next/head'
import { useEffect, lazy } from 'react'
import { useRouter } from 'next/router'
import Search from '../components/inicio/Search'

const Table = lazy(() => import('../components/inicio/Table'))

export default function Home() {
  const { push, query } = useRouter()

  useEffect(() => {
    push('criptos/1')
  }, [])

  return (
    <>
      <Head>
        <title>CrytoTracked</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <>
          <Search />
          {query.id && <Table query={query.id} />}
        </>
      </main>

      <style jsx>
        {`
          main {
            width: 100vw;
          }
          h1 {
            text-align: center;
          }
        `}
      </style>
    </>
  )
}
